### ISSUE TITLE
Convert era string to DateTime object

### ISSUE THREAD

**Issue by giapnhdev** [tomiacannondale/era_ja#21]
We could convert DateTime object to era string but it seems that there is no way to convert from era string to DateTime object.

**Comment by tomiacannondale** [comment]
EraJa can't convert era string to DateTime or Date or Time,  Sorry 😢 

But [wareki](https://github.com/sugi/wareki) can convert era string.
I had not used it, so I don't know how to use it 😭 

If you consider that you convert era string to DateTime by your self, [From ㍻ to U+32FF ](https://speakerdeck.com/mitsuboshi/from-heisei-to-u-plus-32ff) could help you.

**Comment by giapnhdev** [comment]
@tomiacannondale Oh. Thank you so much!
[wareki](url) seems good to me. Sincerely!
